### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by AppleSurgery** [Phoneboard/phoneboard#11]
Hi,

It will be great to run it on MacOS system. I can see You already have it on Linux it will be possible to add option for MacOS? it will be very usefull :)

**Comment by sierra2600** [comment]
So, what I do - since I'm cheap also this is a temporary solution should a real Mac OS version be released - is I have an PC - this should have no problem on a real Mac - with an Intel processor that runs Mac OS 10.8 Mountain Lion - again, this should work on any version from 10.5 or newer - and I have Wine 4.0 Stable (WineHQ.org) with XQuartz 2.7.7 [Required for Wine to function] (XQuartz.org) installed. I then proceed to double click the Windows EXE installer version and Wine Stable will open and you should be able to then install and run it. You will have to make sure to have a display resolution that is wider than 1024 because 1024 will not display all of the tool bar icons... Unless someone knows of a way of natively running the Linux version in Mac OS, since, ya know, Mac OS has a UNIX/Linux foundation to it anyways... ("Who uses macOS?" says my co-workers. Just kidding, just kidding... I only use it for cross-platform software development...)

**Comment by guidopola** [comment]
macOS beta 1 is out in v1.4.2 :)

**Comment by flagsoft** [comment]
Is there a macOS version?
