### ISSUE TITLE
Galaxy S8 schematics doesn't open

### ISSUE THREAD

**Issue by ilGianfri** [Phoneboard/phoneboard#50]
Hi,
I'm using the latest version and I'm unable to view the Galaxy S8 schematics, when I try it doesn't show anything. Everything else works except this model.
I've tried different PCs with no success.

Btw, would it be also possible to add SM-G950F schematics?

Thanks

**Comment by guidopola** [comment]
Thank you for the report 👍. I'm already aware of the issue and it's already fixed. It will be out in the next version ;).

New schematics will have to wait because I'm currently working on the pdf side-by-side schematics so untill I finish working on that I can't work on anything else. Remember that I still work on phoneboard in my free time not full time.

**Comment by guidopola** [comment]
I forgot to close this, this was fixed in v1.4.3
